/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Jan 21 16:06:10 CST 2006 by MyEclipse Hibernate Tool.
 */
package org.mmxbb.bookstore.model;

import java.io.Serializable;

/**
 * A class that represents a row in the category table. 
 * You can customize the behavior of this class by editing the class, {@link Category()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCategory 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the simple categoryname property. */
    private java.lang.String categoryname;

    private Bookinfo bookinfo;
    
    /**
     * Simple constructor of AbstractCategory instances.
     */
    public AbstractCategory()
    {
    }

    /**
     * Constructor of AbstractCategory instances given a simple primary key.
     * @param id
     */
    public AbstractCategory(java.lang.Integer id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Integer id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the categoryname column.
     * @return java.lang.String
     */
    public java.lang.String getCategoryname()
    {
        return this.categoryname;
    }

    /**
     * Set the value of the categoryname column.
     * @param categoryname
     */
    public void setCategoryname(java.lang.String categoryname)
    {
        this.categoryname = categoryname;
    }

    public void setBookinfo(Bookinfo bookinfo){
    	
    	this.bookinfo=bookinfo;
    	
    }
    
    public Bookinfo getBookinfo(){
    	
    	return this.bookinfo;
    }
    
    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Category))
            return false;
        Category that = (Category) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
