/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Jan 21 16:00:43 CST 2006 by MyEclipse Hibernate Tool.
 */
package org.mmxbb.bookstore.model;

import java.io.Serializable;

/**
 * A class that represents a row in the user table. 
 * You can customize the behavior of this class by editing the class, {@link User()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractUser 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the simple loginname property. */
    private java.lang.String loginname;

    /** The value of the simple realname property. */
    private java.lang.String realname;

    /** The value of the simple password property. */
    private java.lang.String password;

    /** The value of the simple phone property. */
    private java.lang.String phone;

    /** The value of the simple address property. */
    private java.lang.String address;

    /** The value of the simple email property. */
    private java.lang.String email;

    /** The value of the simple regtime property. */
    private java.util.Date regtime;

    /**
     * Simple constructor of AbstractUser instances.
     */
    public AbstractUser()
    {
    }

    /**
     * Constructor of AbstractUser instances given a simple primary key.
     * @param id
     */
    public AbstractUser(java.lang.Integer id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Integer id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the loginname column.
     * @return java.lang.String
     */
    public java.lang.String getLoginname()
    {
        return this.loginname;
    }

    /**
     * Set the value of the loginname column.
     * @param loginname
     */
    public void setLoginname(java.lang.String loginname)
    {
        this.loginname = loginname;
    }

    /**
     * Return the value of the realname column.
     * @return java.lang.String
     */
    public java.lang.String getRealname()
    {
        return this.realname;
    }

    /**
     * Set the value of the realname column.
     * @param realname
     */
    public void setRealname(java.lang.String realname)
    {
        this.realname = realname;
    }

    /**
     * Return the value of the password column.
     * @return java.lang.String
     */
    public java.lang.String getPassword()
    {
        return this.password;
    }

    /**
     * Set the value of the password column.
     * @param password
     */
    public void setPassword(java.lang.String password)
    {
        this.password = password;
    }

    /**
     * Return the value of the phone column.
     * @return java.lang.String
     */
    public java.lang.String getPhone()
    {
        return this.phone;
    }

    /**
     * Set the value of the phone column.
     * @param phone
     */
    public void setPhone(java.lang.String phone)
    {
        this.phone = phone;
    }

    /**
     * Return the value of the address column.
     * @return java.lang.String
     */
    public java.lang.String getAddress()
    {
        return this.address;
    }

    /**
     * Set the value of the address column.
     * @param address
     */
    public void setAddress(java.lang.String address)
    {
        this.address = address;
    }

    /**
     * Return the value of the email column.
     * @return java.lang.String
     */
    public java.lang.String getEmail()
    {
        return this.email;
    }

    /**
     * Set the value of the email column.
     * @param email
     */
    public void setEmail(java.lang.String email)
    {
        this.email = email;
    }

    /**
     * Return the value of the regtime column.
     * @return java.util.Date
     */
    public java.util.Date getRegtime()
    {
        return this.regtime;
    }

    /**
     * Set the value of the regtime column.
     * @param regtime
     */
    public void setRegtime(java.util.Date regtime)
    {
        this.regtime = regtime;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof User))
            return false;
        User that = (User) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
