/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Jan 21 16:02:50 CST 2006 by MyEclipse Hibernate Tool.
 */
package org.mmxbb.bookstore.model;

import java.io.Serializable;

/**
 * A class that represents a row in the orderinfo table. 
 * You can customize the behavior of this class by editing the class, {@link Orderinfo()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractOrderinfo 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.String id;

    /** The value of the user association. */
    private Integer userid;

    /** The value of the simple submittime property. */
    private java.util.Date submittime;

    /** The value of the simple totalprice property. */
    private java.lang.Float totalprice;

    /** The value of the simple content property. */
    private java.lang.String content;

    /** The value of the simple ispay property. */
    private java.lang.Integer ispay;

    /** The value of the simple isdeliver property. */
    private java.lang.Integer isdeliver;

    /**
     * Simple constructor of AbstractOrderinfo instances.
     */
    public AbstractOrderinfo()
    {
    }

    /**
     * Constructor of AbstractOrderinfo instances given a simple primary key.
     * @param id
     */
    public AbstractOrderinfo(java.lang.String id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.String
     */
    public java.lang.String getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.String id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the userid column.
     * @return Integer
     */
    public Integer getUserid()
    {
        return this.userid;
    }

    /**
     * Set the value of the userid column.
     * @param userid
     */
    public void setUserid(Integer userid)
    {
        this.userid = userid;
    }

    /**
     * Return the value of the submittime column.
     * @return java.util.Date
     */
    public java.util.Date getSubmittime()
    {
        return this.submittime;
    }

    /**
     * Set the value of the submittime column.
     * @param submittime
     */
    public void setSubmittime(java.util.Date submittime)
    {
        this.submittime = submittime;
    }

    /**
     * Return the value of the totalprice column.
     * @return java.lang.Float
     */
    public java.lang.Float getTotalprice()
    {
        return this.totalprice;
    }

    /**
     * Set the value of the totalprice column.
     * @param totalprice
     */
    public void setTotalprice(java.lang.Float totalprice)
    {
        this.totalprice = totalprice;
    }

    /**
     * Return the value of the content column.
     * @return java.lang.String
     */
    public java.lang.String getContent()
    {
        return this.content;
    }

    /**
     * Set the value of the content column.
     * @param content
     */
    public void setContent(java.lang.String content)
    {
        this.content = content;
    }

    /**
     * Return the value of the ispay column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getIspay()
    {
        return this.ispay;
    }

    /**
     * Set the value of the ispay column.
     * @param ispay
     */
    public void setIspay(java.lang.Integer ispay)
    {
        this.ispay = ispay;
    }

    /**
     * Return the value of the isdeliver column.
     * @return java.lang.String
     */
    public java.lang.Integer getIsdeliver()
    {
        return this.isdeliver;
    }

    /**
     * Set the value of the isdeliver column.
     * @param isdeliver
     */
    public void setIsdeliver(java.lang.Integer isdeliver)
    {
        this.isdeliver = isdeliver;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Orderinfo))
            return false;
        Orderinfo that = (Orderinfo) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
